language: java

jdk:
- oraclejdk8

sudo: required

services:
- docker

before_install:
- export CHROME_BIN=chromium-browser
- export DISPLAY=:99.0
- sh -e /etc/init.d/xvfb start

install: true

cache:
  directories:
  - frontend-angularjs/node_modules
  - frontend-angularjs/node_modules
  - $HOME/.m2

before_script:
- npm install -g jspm
- jspm config registries.github.auth $JSPM_GITHUB_AUTH_TOKEN

script:
- ./mvnw -f frontend-angularjs/pom.xml install
- ./mvnw -f backend/pom.xml install jacoco:report
- ./mvnw -f frontend-angular/pom.xml install

after_success:
- ./mvnw -f backend/pom.xml coveralls:report
- ./docker-build.sh
- docker login -u $DOCKER_USER -p $DOCKER_PASS
- docker push davinkevin/podcast-server

before_deploy:
- ./mvnw install -DskipTests=true

deploy:
  provider: releases
  skip_cleanup: true
  api_key:
    secure: X9W0MGueni+7ly75mS+NtEAWzJWaD1CZxOtf2OBYQ0wDVABzTO2gztSQjSwgttThrwEVWeAKS7TUE8WUHSpqGoD5pkfKwOMgyiX2angPWuvtWvBgguzuxdNAiQxMVVC+0KOVcXdeuvSMt69HjoVQVa0IKOqkRDwle6U2bQXSrOk=
  file: backend/target/Podcast-Server.jar
  on:
    repo: davinkevin/Podcast-Server
    tags: true

env:
  global:
  - secure: JHRJqotNNwyyD6zYSXXwzE7Jsw2XdMKl2sxWFGK+SUgBw5ecG6eFnuFUQ01hLGSckqGiRZeVGH5wMrxC2ne5J1dstaWGSGvHzQEKbRQpd1ZXaTZ+i/gofunHWlWBKgrhO8/SprSs4jVeP0r3ZMxKDiUhl2oxBMu3OhcLiyyY1Dk=
  - secure: cxY/vp09qJWSwV80HPwoGvH2Ms93vzJnIvimNbBPD3C0MxkjaXSMeLoE/IsikbYj3wyAcNw+CQDjW4GsHMcb7s+DgKhW+DPRT2WPVr8ZkLBBvGbWPnIy/55jqFrNoLnL6jcbLoVTKCkjQGy+y4plCdn2TDexJGfEokOvkTRColg=
  - secure: L6VmZ5G+rC55sYhmiVip/KfAwy+vWStq/Rn4BhMUw+g5lG+Nbu67C0a+62loHeqhN9GENwovtzcTd7PqcJO9I07L8d/SgnAKgzn1jp+ozjZDJiOMqKURd3qa3LZpGueKrO2tjBIbE6hiReQxm0HrVNZeFCN7DXTDawVKhxbDznE=
